CC = gcc
CFLAGS = -Iheaders
SRCS = src/checkCandidateSkills.c src/main.c
OBJS = $(SRCS:.c=.o)

all : checkCandidateSkills

checkCandidateSkills: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o checkCandidateSkills

clean:
	rm -f src/*.o checkCandidateSkills